version: "3.8"
services:

  sge-container:
    environment:
      TARGET_GRID_ENGINE: SGE
    build:
      context: ../..
      dockerfile: ./docker/sge/Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
